# Generated by Django 4.0.4 on 2022-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_image_options_remove_image_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
